package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Antivirus generated by hbm2java
 */
@Entity
@Table(name = "antivirus", catalog = "inventario")
public class Antivirus implements java.io.Serializable {

	private Integer idAntivirus;
	private String marca;
	private List<Cpu> cpus = new ArrayList<>();

	public Antivirus() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_antivirus", unique = true, nullable = false)
	public Integer getIdAntivirus() {
		return this.idAntivirus;
	}

	public void setIdAntivirus(Integer idAntivirus) {
		this.idAntivirus = idAntivirus;
	}

	@Column(name = "marca", nullable = false, length = 250)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@OneToMany(mappedBy = "antivirus")
	public List<Cpu> getCpus() {
		return this.cpus;
	}

	public void setCpus(List<Cpu> cpus) {
		this.cpus = cpus;
	}

}
