package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;

/**
 * Dispositivo generated by hbm2java
 */
@Entity
@Table(name = "dispositivo", catalog = "inventario")
public class Dispositivo implements java.io.Serializable {

	private Integer idDispositivo;
	private Estado estado;
	private TipoDispositivo tipoDispositivo;
	private Ubicacion ubicacion;
	private String marca;
	private String codBarras;
	private String modelo;
	private String serie;
	private String observacion;
	private Integer idDispasoc;
	private Date fecMod;
	private Date fechReg;
	private List<RecursoDispositivo> recursoDispositivos = new ArrayList<>();
	private Cpu cpu;
	private List<DispositivoUsuario> dispositivoUsuarios = new ArrayList<>();
	private String urImagen;

	public Dispositivo() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dispositivo", unique = true, nullable = false)
	public Integer getIdDispositivo() {
		return this.idDispositivo;
	}

	public void setIdDispositivo(Integer idDispositivo) {
		this.idDispositivo = idDispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "estado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne
	@JoinColumn(name = "id_tipodispositivo", nullable = false)
	public TipoDispositivo getTipoDispositivo() {
		return this.tipoDispositivo;
	}

	public void setTipoDispositivo(TipoDispositivo tipoDispositivo) {
		this.tipoDispositivo = tipoDispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "id_ubicacion")
	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "marca", length = 100)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "cod_barras", length = 10)
	public String getCodBarras() {
		return this.codBarras;
	}

	public void setCodBarras(String codBarras) {
		this.codBarras = codBarras;
	}

	@Column(name = "modelo", length = 250)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "serie", length = 250)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "observacion", length = 50000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "id_dispasoc")
	public Integer getIdDispasoc() {
		return this.idDispasoc;
	}

	public void setIdDispasoc(Integer idDispasoc) {
		this.idDispasoc = idDispasoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_mod", length = 26)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@OneToMany(mappedBy = "dispositivo")
	public List<RecursoDispositivo> getRecursoDispositivos() {
		return this.recursoDispositivos;
	}

	public void setRecursoDispositivos(List<RecursoDispositivo> recursoDispositivos) {
		this.recursoDispositivos = recursoDispositivos;
	}

	@OneToOne(mappedBy = "dispositivo")
	public Cpu getCpu() {
		return this.cpu;
	}

	public void setCpu(Cpu cpu) {
		this.cpu = cpu;
	}

	@OneToMany(mappedBy = "dispositivo")
	public List<DispositivoUsuario> getDispositivoUsuarios() {
		return this.dispositivoUsuarios;
	}

	public void setDispositivoUsuarios(List<DispositivoUsuario> dispositivoUsuarios) {
		this.dispositivoUsuarios = dispositivoUsuarios;
	}

	@Column(name = "fec_reg")
	public Date getFechReg() {
		return fechReg;
	}

	public void setFechReg(Date fechReg) {
		this.fechReg = fechReg;
	}

	@Column(name = "ur_imagen")
	@Type(type = "text")
	public String getUrImagen() {
		return urImagen;
	}

	public void setUrImagen(String urImagen) {
		this.urImagen = urImagen;
	}
	
	

}
