package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DispositivoUsuario generated by hbm2java
 */
@Entity
@Table(name = "dispositivo_usuario", catalog = "inventario")
public class DispositivoUsuario implements java.io.Serializable {

	private Integer idDisUsu;
	private Condicion condicion;
	private Dispositivo dispositivo;
	private TipoImpresora tipoImpresora;
	private UsuarioUbicacion usuarioUbicacion;
	private Date fecMod;
	private String observacion;

	public DispositivoUsuario() {
	}

	public DispositivoUsuario(Condicion condicion, Dispositivo dispositivo) {
		this.condicion = condicion;
		this.dispositivo = dispositivo;
	}

	public DispositivoUsuario(Condicion condicion, Dispositivo dispositivo, TipoImpresora tipoImpresora,
			UsuarioUbicacion usuarioUbicacion, Date fecMod, String observacion) {
		this.condicion = condicion;
		this.dispositivo = dispositivo;
		this.tipoImpresora = tipoImpresora;
		this.usuarioUbicacion = usuarioUbicacion;
		this.fecMod = fecMod;
		this.observacion = observacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dis_usu", unique = true, nullable = false)
	public Integer getIdDisUsu() {
		return this.idDisUsu;
	}

	public void setIdDisUsu(Integer idDisUsu) {
		this.idDisUsu = idDisUsu;
	}

	@ManyToOne
	@JoinColumn(name = "condicion", nullable = false)
	public Condicion getCondicion() {
		return this.condicion;
	}

	public void setCondicion(Condicion condicion) {
		this.condicion = condicion;
	}

	@ManyToOne
	@JoinColumn(name = "id_dispositivo", nullable = false)
	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "id_tipoimpresora")
	public TipoImpresora getTipoImpresora() {
		return this.tipoImpresora;
	}

	public void setTipoImpresora(TipoImpresora tipoImpresora) {
		this.tipoImpresora = tipoImpresora;
	}

	@ManyToOne
	@JoinColumn(name = "id_usu_ubi")
	public UsuarioUbicacion getUsuarioUbicacion() {
		return this.usuarioUbicacion;
	}

	public void setUsuarioUbicacion(UsuarioUbicacion usuarioUbicacion) {
		this.usuarioUbicacion = usuarioUbicacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_mod", length = 26)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "observacion", length = 50000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
