package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", catalog = "inventario")
public class Division implements java.io.Serializable {

	private Integer idDivision;
	private String nomDivision;
	private List<Ubicacion> ubicacions = new ArrayList<Ubicacion>();

	public Division() {
	}

	public Division(String nomDivision) {
		this.nomDivision = nomDivision;
	}

	public Division(String nomDivision, List<Ubicacion> ubicacions) {
		this.nomDivision = nomDivision;
		this.ubicacions = ubicacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_division", unique = true, nullable = false)
	public Integer getIdDivision() {
		return this.idDivision;
	}

	public void setIdDivision(Integer idDivision) {
		this.idDivision = idDivision;
	}

	@Column(name = "nom_division", nullable = false, length = 250)
	public String getNomDivision() {
		return this.nomDivision;
	}

	public void setNomDivision(String nomDivision) {
		this.nomDivision = nomDivision;
	}

	@OneToMany(mappedBy = "division")
	public List<Ubicacion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(List<Ubicacion> ubicacions) {
		this.ubicacions = ubicacions;
	}

}
