package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dominio generated by hbm2java
 */
@Entity
@Table(name = "dominio", catalog = "inventario")
public class Dominio implements java.io.Serializable {

	private Integer idDominio;
	private String nomDominio;
	private List<UsuarioUbicacion> usuarioUbicacions = new ArrayList<>();

	public Dominio() {
	}

	public Dominio(String nomDominio) {
		this.nomDominio = nomDominio;
	}

	public Dominio(String nomDominio, List<UsuarioUbicacion> usuarioUbicacions) {
		this.nomDominio = nomDominio;
		this.usuarioUbicacions = usuarioUbicacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dominio", unique = true, nullable = false)
	public Integer getIdDominio() {
		return this.idDominio;
	}

	public void setIdDominio(Integer idDominio) {
		this.idDominio = idDominio;
	}

	@Column(name = "nom_dominio", nullable = false, length = 100)
	public String getNomDominio() {
		return this.nomDominio;
	}

	public void setNomDominio(String nomDominio) {
		this.nomDominio = nomDominio;
	}

	@OneToMany(mappedBy = "dominio")
	public List<UsuarioUbicacion> getUsuarioUbicacions() {
		return this.usuarioUbicacions;
	}

	public void setUsuarioUbicacions(List<UsuarioUbicacion> usuarioUbicacions) {
		this.usuarioUbicacions = usuarioUbicacions;
	}

}
