package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "inventario")
public class Estado implements java.io.Serializable {

	private Integer idEstado;
	private String nomEstado;
	private List<Recurso> recursos = new ArrayList<Recurso>();
	private List<Dispositivo> dispositivos = new ArrayList<Dispositivo>();

	public Estado() {
	}

	public Estado(String nomEstado) {
		this.nomEstado = nomEstado;
	}

	public Estado(String nomEstado, List<Recurso> recursos, List<Dispositivo> dispositivos) {
		this.nomEstado = nomEstado;
		this.recursos = recursos;
		this.dispositivos = dispositivos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estado", unique = true, nullable = false)
	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "nom_estado", nullable = false, length = 100)
	public String getNomEstado() {
		return this.nomEstado;
	}

	public void setNomEstado(String nomEstado) {
		this.nomEstado = nomEstado;
	}

	@OneToMany(mappedBy = "estado")
	public List<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(List<Recurso> recursos) {
		this.recursos = recursos;
	}

	@OneToMany(mappedBy = "estado")
	public List<Dispositivo> getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(List<Dispositivo> dispositivos) {
		this.dispositivos = dispositivos;
	}

}
