package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "inventario")
public class Proveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idProveedor;
	private String tipoDocumento;
	private String nroDocumento;
	private String nomProveedor;
	private String observacion;
	private List<Servicio> serviciosForIdPartner = new ArrayList<Servicio>(0);
	private List<Servicio> serviciosForIdProveedor = new ArrayList<Servicio>(0);

	public Proveedor() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_proveedor", unique = true, nullable = false)
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "nom_proveedor", length = 1000)
	public String getNomProveedor() {
		return this.nomProveedor;
	}

	public void setNomProveedor(String nomProveedor) {
		this.nomProveedor = nomProveedor;
	}

	@Column(name = "observacion", nullable = false, length = 50000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@OneToMany(mappedBy = "proveedorByIdPartner")
	public List<Servicio> getServiciosForIdPartner() {
		return this.serviciosForIdPartner;
	}

	public void setServiciosForIdPartner(List<Servicio> serviciosForIdPartner) {
		this.serviciosForIdPartner = serviciosForIdPartner;
	}

	@OneToMany(mappedBy = "proveedorByIdProveedor")
	public List<Servicio> getServiciosForIdProveedor() {
		return this.serviciosForIdProveedor;
	}

	public void setServiciosForIdProveedor(List<Servicio> serviciosForIdProveedor) {
		this.serviciosForIdProveedor = serviciosForIdProveedor;
	}

	@Column(name = "tipo_documento")
	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "nro_documento")
	public String getNroDocumento() {
		return nroDocumento;
	}

	public void setNroDocumento(String nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

}
