package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecursoDispositivo generated by hbm2java
 */
@Entity
@Table(name = "recurso_dispositivo", catalog = "inventario")
public class RecursoDispositivo implements java.io.Serializable {

	private Integer idRecDis;
	private Condicion condicion;
	private Dispositivo dispositivo;
	private Recurso recurso;
	private Date fecMod;
	private List<DispositivoIp> dispositivoIps = new ArrayList<DispositivoIp>(0);

	public RecursoDispositivo() {
	}

	public RecursoDispositivo(Condicion condicion, Dispositivo dispositivo, Recurso recurso, Date fecMod) {
		this.condicion = condicion;
		this.dispositivo = dispositivo;
		this.recurso = recurso;
		this.fecMod = fecMod;
	}

	public RecursoDispositivo(Condicion condicion, Dispositivo dispositivo, Recurso recurso, Date fecMod,
			List<DispositivoIp> dispositivoIps) {
		this.condicion = condicion;
		this.dispositivo = dispositivo;
		this.recurso = recurso;
		this.fecMod = fecMod;
		this.dispositivoIps = dispositivoIps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_rec_dis", unique = true, nullable = false)
	public Integer getIdRecDis() {
		return this.idRecDis;
	}

	public void setIdRecDis(Integer idRecDis) {
		this.idRecDis = idRecDis;
	}

	@ManyToOne
	@JoinColumn(name = "condicion", nullable = false)
	public Condicion getCondicion() {
		return this.condicion;
	}

	public void setCondicion(Condicion condicion) {
		this.condicion = condicion;
	}

	@ManyToOne
	@JoinColumn(name = "id_dispositivo", nullable = false)
	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	@ManyToOne
	@JoinColumn(name = "id_recurso", nullable = false)
	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fec_mod", nullable = false, length = 26)
	public Date getFecMod() {
		return this.fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@OneToMany(mappedBy = "recursoDispositivo")
	public List<DispositivoIp> getDispositivoIps() {
		return this.dispositivoIps;
	}

	public void setDispositivoIps(List<DispositivoIp> dispositivoIps) {
		this.dispositivoIps = dispositivoIps;
	}

}
