package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede", catalog = "inventario")
public class Sede implements java.io.Serializable {

	private Integer idSede;
	private String nomSede;
	private List<Ubicacion> ubicacions = new ArrayList<>();

	public Sede() {
	}

	public Sede(String nomSede) {
		this.nomSede = nomSede;
	}

	public Sede(String nomSede, List<Ubicacion> ubicacions) {
		this.nomSede = nomSede;
		this.ubicacions = ubicacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_sede", unique = true, nullable = false)
	public Integer getIdSede() {
		return this.idSede;
	}

	public void setIdSede(Integer idSede) {
		this.idSede = idSede;
	}

	@Column(name = "nom_sede", nullable = false, length = 250)
	public String getNomSede() {
		return this.nomSede;
	}

	public void setNomSede(String nomSede) {
		this.nomSede = nomSede;
	}

	@OneToMany(mappedBy = "sede")
	public List<Ubicacion> getUbicacions() {
		return this.ubicacions;
	}

	public void setUbicacions(List<Ubicacion> ubicacions) {
		this.ubicacions = ubicacions;
	}

}
