package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio", catalog = "inventario")
public class Servicio implements java.io.Serializable {

	private Integer idServicio;
	private Condicion condicion;
	private Proveedor proveedorByIdPartner;
	private Proveedor proveedorByIdProveedor;
	private Software software;
	private TipoLicencia tipoLicencia;
	private Ubicacion ubicacion;
	private Date fecInicio;
	private Date fecExpiracion;
	private String orden;
	private String observacion;
	private String renovacion;

	public Servicio() {
	}

	public Servicio(Condicion condicion, Proveedor proveedorByIdProveedor, Software software, TipoLicencia tipoLicencia,
			Ubicacion ubicacion, Date fecInicio, Date fecExpiracion, String renovacion) {
		this.condicion = condicion;
		this.proveedorByIdProveedor = proveedorByIdProveedor;
		this.software = software;
		this.tipoLicencia = tipoLicencia;
		this.ubicacion = ubicacion;
		this.fecInicio = fecInicio;
		this.fecExpiracion = fecExpiracion;
		this.renovacion = renovacion;
	}

	public Servicio(Condicion condicion, Proveedor proveedorByIdPartner, Proveedor proveedorByIdProveedor,
			Software software, TipoLicencia tipoLicencia, Ubicacion ubicacion, Date fecInicio, Date fecExpiracion,
			String orden, String observacion, String renovacion) {
		this.condicion = condicion;
		this.proveedorByIdPartner = proveedorByIdPartner;
		this.proveedorByIdProveedor = proveedorByIdProveedor;
		this.software = software;
		this.tipoLicencia = tipoLicencia;
		this.ubicacion = ubicacion;
		this.fecInicio = fecInicio;
		this.fecExpiracion = fecExpiracion;
		this.orden = orden;
		this.observacion = observacion;
		this.renovacion = renovacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_servicio", unique = true, nullable = false)
	public Integer getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(Integer idServicio) {
		this.idServicio = idServicio;
	}

	@ManyToOne
	@JoinColumn(name = "condicion", nullable = false)
	public Condicion getCondicion() {
		return this.condicion;
	}

	public void setCondicion(Condicion condicion) {
		this.condicion = condicion;
	}

	@ManyToOne
	@JoinColumn(name = "id_partner")
	public Proveedor getProveedorByIdPartner() {
		return this.proveedorByIdPartner;
	}

	public void setProveedorByIdPartner(Proveedor proveedorByIdPartner) {
		this.proveedorByIdPartner = proveedorByIdPartner;
	}

	@ManyToOne
	@JoinColumn(name = "id_proveedor", nullable = false)
	public Proveedor getProveedorByIdProveedor() {
		return this.proveedorByIdProveedor;
	}

	public void setProveedorByIdProveedor(Proveedor proveedorByIdProveedor) {
		this.proveedorByIdProveedor = proveedorByIdProveedor;
	}

	@ManyToOne
	@JoinColumn(name = "id_software", nullable = false)
	public Software getSoftware() {
		return this.software;
	}

	public void setSoftware(Software software) {
		this.software = software;
	}

	@ManyToOne
	@JoinColumn(name = "id_tipolicencia", nullable = false)
	public TipoLicencia getTipoLicencia() {
		return this.tipoLicencia;
	}

	public void setTipoLicencia(TipoLicencia tipoLicencia) {
		this.tipoLicencia = tipoLicencia;
	}

	@ManyToOne
	@JoinColumn(name = "id_ubicacion", nullable = false)
	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fec_inicio", nullable = false, length = 10)
	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fec_expiracion", nullable = false, length = 10)
	public Date getFecExpiracion() {
		return this.fecExpiracion;
	}

	public void setFecExpiracion(Date fecExpiracion) {
		this.fecExpiracion = fecExpiracion;
	}

	@Column(name = "orden", length = 500)
	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	@Column(name = "observacion", length = 50000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "renovacion", nullable = false, length = 50)
	public String getRenovacion() {
		return this.renovacion;
	}

	public void setRenovacion(String renovacion) {
		this.renovacion = renovacion;
	}

}
