package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Software generated by hbm2java
 */
@Entity
@Table(name = "software", catalog = "inventario")
public class Software implements java.io.Serializable {

	private Integer idSoftware;
	private String nomSoftware;
	private String observacion;
	private List<Servicio> servicios = new ArrayList<Servicio>();

	public Software() {
	}

	public Software(String nomSoftware, String observacion) {
		this.nomSoftware = nomSoftware;
		this.observacion = observacion;
	}

	public Software(String nomSoftware, String observacion, List<Servicio> servicios) {
		this.nomSoftware = nomSoftware;
		this.observacion = observacion;
		this.servicios = servicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_software", unique = true, nullable = false)
	public Integer getIdSoftware() {
		return this.idSoftware;
	}

	public void setIdSoftware(Integer idSoftware) {
		this.idSoftware = idSoftware;
	}

	@Column(name = "nom_software", nullable = false, length = 1000)
	public String getNomSoftware() {
		return this.nomSoftware;
	}

	public void setNomSoftware(String nomSoftware) {
		this.nomSoftware = nomSoftware;
	}

	@Column(name = "observacion", nullable = false, length = 50000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@OneToMany( mappedBy = "software")
	public List<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(List<Servicio> servicios) {
		this.servicios = servicios;
	}

}
