package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoLicencia generated by hbm2java
 */
@Entity
@Table(name = "tipo_licencia", catalog = "inventario")
public class TipoLicencia implements java.io.Serializable {

	private Integer idTipolicencia;
	private String nomTipolicencia;
	private List<Servicio> servicios = new ArrayList<>();

	public TipoLicencia() {
	}

	public TipoLicencia(String nomTipolicencia) {
		this.nomTipolicencia = nomTipolicencia;
	}

	public TipoLicencia(String nomTipolicencia, List<Servicio> servicios) {
		this.nomTipolicencia = nomTipolicencia;
		this.servicios = servicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipolicencia", unique = true, nullable = false)
	public Integer getIdTipolicencia() {
		return this.idTipolicencia;
	}

	public void setIdTipolicencia(Integer idTipolicencia) {
		this.idTipolicencia = idTipolicencia;
	}

	@Column(name = "nom_tipolicencia", nullable = false, length = 100)
	public String getNomTipolicencia() {
		return this.nomTipolicencia;
	}

	public void setNomTipolicencia(String nomTipolicencia) {
		this.nomTipolicencia = nomTipolicencia;
	}

	@OneToMany(mappedBy = "tipoLicencia")
	public List<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(List<Servicio> servicios) {
		this.servicios = servicios;
	}

}
