package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDispositivo generated by hbm2java
 */
@Entity
@Table(name = "tipo_dispositivo", catalog = "inventario")
public class TipoDispositivo implements java.io.Serializable {

	private Integer idTipodispositivo;
	private String nomDispositivo;
	private Date fechaRegistro;
	private List<Dispositivo> dispositivos = new ArrayList<>();

	public TipoDispositivo() {
	}

	public TipoDispositivo(String nomDispositivo) {
		this.nomDispositivo = nomDispositivo;
	}

	public TipoDispositivo(String nomDispositivo, List<Dispositivo> dispositivos) {
		this.nomDispositivo = nomDispositivo;
		this.dispositivos = dispositivos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipodispositivo", unique = true, nullable = false)
	public Integer getIdTipodispositivo() {
		return this.idTipodispositivo;
	}

	public void setIdTipodispositivo(Integer idTipodispositivo) {
		this.idTipodispositivo = idTipodispositivo;
	}

	@Column(name = "nom_dispositivo", nullable = false, length = 250)
	public String getNomDispositivo() {
		return this.nomDispositivo;
	}

	public void setNomDispositivo(String nomDispositivo) {
		this.nomDispositivo = nomDispositivo;
	}

	@OneToMany(mappedBy = "tipoDispositivo")
	public List<Dispositivo> getDispositivos() {
		return this.dispositivos;
	}
	
	public void setDispositivos(List<Dispositivo> dispositivos) {
		this.dispositivos = dispositivos;
	}

	@Column(name ="fecha_registro")
	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
