package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoLogueo generated by hbm2java
 */
@Entity
@Table(name = "tipo_logueo", catalog = "inventario")
public class TipoLogueo implements java.io.Serializable {

	private Integer idTipologueo;
	private String nomTipologueo;
	private List<Logueo> logueos = new ArrayList<>();

	public TipoLogueo() {
	}

	public TipoLogueo(String nomTipologueo) {
		this.nomTipologueo = nomTipologueo;
	}

	public TipoLogueo(String nomTipologueo, List<Logueo> logueos) {
		this.nomTipologueo = nomTipologueo;
		this.logueos = logueos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipologueo", unique = true, nullable = false)
	public Integer getIdTipologueo() {
		return this.idTipologueo;
	}

	public void setIdTipologueo(Integer idTipologueo) {
		this.idTipologueo = idTipologueo;
	}

	@Column(name = "nom_tipologueo", nullable = false, length = 100)
	public String getNomTipologueo() {
		return this.nomTipologueo;
	}

	public void setNomTipologueo(String nomTipologueo) {
		this.nomTipologueo = nomTipologueo;
	}

	@OneToMany(mappedBy = "tipoLogueo")
	public List<Logueo> getLogueos() {
		return this.logueos;
	}

	public void setLogueos(List<Logueo> logueos) {
		this.logueos = logueos;
	}

}
