package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoImpresora generated by hbm2java
 */
@Entity
@Table(name = "tipo_impresora", catalog = "inventario")
public class TipoImpresora implements java.io.Serializable {

	private Integer idTipoimpresora;
	private String nomTipoimpresora;
	private List<DispositivoUsuario> dispositivoUsuarios = new ArrayList<>();

	public TipoImpresora() {
	}

	public TipoImpresora(String nomTipoimpresora) {
		this.nomTipoimpresora = nomTipoimpresora;
	}

	public TipoImpresora(String nomTipoimpresora, List<DispositivoUsuario> dispositivoUsuarios) {
		this.nomTipoimpresora = nomTipoimpresora;
		this.dispositivoUsuarios = dispositivoUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipoimpresora", unique = true, nullable = false)
	public Integer getIdTipoimpresora() {
		return this.idTipoimpresora;
	}

	public void setIdTipoimpresora(Integer idTipoimpresora) {
		this.idTipoimpresora = idTipoimpresora;
	}

	@Column(name = "nom_tipoimpresora", nullable = false, length = 250)
	public String getNomTipoimpresora() {
		return this.nomTipoimpresora;
	}

	public void setNomTipoimpresora(String nomTipoimpresora) {
		this.nomTipoimpresora = nomTipoimpresora;
	}

	@OneToMany(mappedBy = "tipoImpresora")
	public List<DispositivoUsuario> getDispositivoUsuarios() {
		return this.dispositivoUsuarios;
	}

	public void setDispositivoUsuarios(List<DispositivoUsuario> dispositivoUsuarios) {
		this.dispositivoUsuarios = dispositivoUsuarios;
	}

}
