package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoRecurso generated by hbm2java
 */
@Entity
@Table(name = "tipo_recurso", catalog = "inventario")
public class TipoRecurso implements java.io.Serializable {

	private Integer idTiporecurso;
	private String nomTiporecurso;
	private List<Recurso> recursos = new ArrayList<>();

	public TipoRecurso() {
	}

	public TipoRecurso(String nomTiporecurso) {
		this.nomTiporecurso = nomTiporecurso;
	}

	public TipoRecurso(String nomTiporecurso, List<Recurso> recursos) {
		this.nomTiporecurso = nomTiporecurso;
		this.recursos = recursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tiporecurso", unique = true, nullable = false)
	public Integer getIdTiporecurso() {
		return this.idTiporecurso;
	}

	public void setIdTiporecurso(Integer idTiporecurso) {
		this.idTiporecurso = idTiporecurso;
	}

	@Column(name = "nom_tiporecurso", nullable = false, length = 250)
	public String getNomTiporecurso() {
		return this.nomTiporecurso;
	}

	public void setNomTiporecurso(String nomTiporecurso) {
		this.nomTiporecurso = nomTiporecurso;
	}

	@OneToMany(mappedBy = "tipoRecurso")
	public List<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(List<Recurso> recursos) {
		this.recursos = recursos;
	}

}
