package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubicacion generated by hbm2java
 */
@Entity
@Table(name = "ubicacion", catalog = "inventario")
public class Ubicacion implements java.io.Serializable {

	private Integer idUbicacion;
	private Division division;
	private Oficina oficina;
	private Sede sede;
	private List<Dispositivo> dispositivos = new ArrayList<>();
	private List<UsuarioUbicacion> usuarioUbicacions = new ArrayList<>();
	private List<Servicio> servicios = new ArrayList<>(0);

	public Ubicacion() {
	}

	public Ubicacion(Division division, Oficina oficina, Sede sede) {
		this.division = division;
		this.oficina = oficina;
		this.sede = sede;
	}

	public Ubicacion(Division division, Oficina oficina, Sede sede, List<Dispositivo> dispositivos,
			List<UsuarioUbicacion> usuarioUbicacions, List<Servicio> servicios) {
		this.division = division;
		this.oficina = oficina;
		this.sede = sede;
		this.dispositivos = dispositivos;
		this.usuarioUbicacions = usuarioUbicacions;
		this.servicios = servicios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ubicacion", unique = true, nullable = false)
	public Integer getIdUbicacion() {
		return this.idUbicacion;
	}

	public void setIdUbicacion(Integer idUbicacion) {
		this.idUbicacion = idUbicacion;
	}

	@ManyToOne
	@JoinColumn(name = "id_division", nullable = false)
	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	@ManyToOne
	@JoinColumn(name = "id_oficina", nullable = false)
	public Oficina getOficina() {
		return this.oficina;
	}

	public void setOficina(Oficina oficina) {
		this.oficina = oficina;
	}

	@ManyToOne
	@JoinColumn(name = "id_sede", nullable = false)
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@OneToMany(mappedBy = "ubicacion")
	public List<Dispositivo> getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(List<Dispositivo> dispositivos) {
		this.dispositivos = dispositivos;
	}

	@OneToMany(mappedBy = "ubicacion")
	public List<UsuarioUbicacion> getUsuarioUbicacions() {
		return this.usuarioUbicacions;
	}

	public void setUsuarioUbicacions(List<UsuarioUbicacion> usuarioUbicacions) {
		this.usuarioUbicacions = usuarioUbicacions;
	}

	@OneToMany(mappedBy = "ubicacion")
	public List<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(List<Servicio> servicios) {
		this.servicios = servicios;
	}

}
