package pe.com.utp.inventario.entities;
// Generated 30/04/2020 08:56:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "inventario")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private String nombres;
	private String ape1;
	private String ape2;
	private String usuRed;
	private Date fecMod;
	private List<Logueo> logueos = new ArrayList<>();
	private List<UsuarioUbicacion> usuarioUbicacions = new ArrayList<UsuarioUbicacion>();
	private String estado;

	public Usuario() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nombres", nullable = false, length = 500)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "ape1", length = 500)
	public String getApe1() {
		return this.ape1;
	}

	public void setApe1(String ape1) {
		this.ape1 = ape1;
	}

	@Column(name = "ape2", length = 500)
	public String getApe2() {
		return this.ape2;
	}

	public void setApe2(String ape2) {
		this.ape2 = ape2;
	}

	@Column(name = "usu_red", nullable = false, length = 100)
	public String getUsuRed() {
		return this.usuRed;
	}

	public void setUsuRed(String usuRed) {
		this.usuRed = usuRed;
	}

	@OneToMany(mappedBy = "usuario")
	public List<Logueo> getLogueos() {
		return this.logueos;
	}

	public void setLogueos(List<Logueo> logueos) {
		this.logueos = logueos;
	}

	@OneToMany(mappedBy = "usuario")
	public List<UsuarioUbicacion> getUsuarioUbicacions() {
		return this.usuarioUbicacions;
	}

	public void setUsuarioUbicacions(List<UsuarioUbicacion> usuarioUbicacions) {
		this.usuarioUbicacions = usuarioUbicacions;
	}

	@Column(name = "fec_mod")
	public Date getFecMod() {
		return fecMod;
	}

	public void setFecMod(Date fecMod) {
		this.fecMod = fecMod;
	}

	@Column(name = "estado")
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
